### ISSUE TITLE
Use with ONT duplex data

### ISSUE THREAD

**Issue by touala** [maickrau/ribotin#1]
Hello @maickrau,

Thank you for sharing your work. Would it be technically possible to use `ribotin` on Nanopore duplex dataset (Q30) or does Hifi reads are mandatory?

Unrelated, what is the most up-to-date map of CHM13 rDNA loci? Is it still the version released with the main CHM13 T2T genome paper (v1.1)?

Best,

Alan

**Comment by maickrau** [comment]
Duplex reads seem to work. The most recent CHM13 rDNA locatinos should be in the UCSC genome browser. They're also extracted in this repo at `template_seqs/chm13_rDNAs.fa`

**Comment by touala** [comment]
Thank you for the quick response.
