### ISSUE TITLE
An assertion failure in ClusterHandler.cpp when assembling repeat regions

### ISSUE THREAD

**Issue by zhang-shilong** [maickrau/ribotin#5]
Hello, @maickrau 

I tried using ribotin on rDNA regions and it worked well. Thank you for sharing such a meaningful work.

I wondered if it would work for repeat regions, such as subtelomeres. I extracted a subtelomeric region that was collapsed by both Hifiasm and Verkko. Unfortunately, an assertion failure occurred.

My command:
```
/software/ribotin-3d33151/bin/ribotin-ref \
        -r chr10:1-800000.fasta \
        -o . \
        --mbg /path/to/MBG \
        -i <hifi_reads> \
        --orient-by-reference chr10:1-800000.fasta \
        --nano <ont_reads>
```

Error message:
```
ribotin-ref version Branch master commit 3d33151627b9c2f1ab9ab308c50a8f5cdb6b0f79 2023-05-05 14:19:09 +0300
checking for GraphAligner
output folder: .
extracting HiFi/duplex reads
extracting ultralong ONT reads
running
running MBG
MBG command:
/path/to/MBG -o ./graph.gfa -i ./hifi_reads.fa -k 101 -w 71 -a 2 -u 3 -r 15000 -R 4000 --error-masking=msat --output-sequence-paths ./paths.gaf --only-local-resolve 1> ./mbg_stdout.txt 2> ./mbg_stderr.txt
reading graph
getting consensus
ribotin-ref: src/ClusterHandler.cpp:406: Path getHeavyPath(const GfaGraph&): Assertion `result.overlaps.size() == result.nodes.size()' failed.
/tmp/slurmd/job24926730/slurm_script: line 15: 3729284 Aborted                 (core dumped)
```

NucFreq plot on chr10:1-5m:

![chr10_0-5000000](https://github.com/maickrau/ribotin/assets/87555514/128bc289-3fec-479b-9929-1918ae908f7e)

Can ribotin assemble such complex regions, or is there an issue with my usage?

Best wishes.

**Comment by maickrau** [comment]
Hi, could you upload the output folder?

**Comment by zhang-shilong** [comment]
Of course. I sent the link to your hotmail.

**Comment by maickrau** [comment]
The repeat region has palindromic repeats which the consensus path algorithm can't handle. So unfortunately ribotin can't help here. The latest version now prints a more useful error message when this happens.
