### ISSUE TITLE
Bug when running ribotin-verkko on non-rukki asm

### ISSUE THREAD

**Issue by steven-solar** [maickrau/ribotin#7]
Running ribotin on chm13, and fails with `ribotin-verkko: src/VerkkoReadAssignment.cpp:26: bool getRukkiEnabled(std::string): Assertion 'false' failed.` I believe the issue is that `getRukkiEnabled` doesn't allow for the case of an older `verkko.yml` file not having the `ruk_enable` line, but I think in this case it should also just return false.

**Comment by maickrau** [comment]
sounds reasonable, commit [298c715](https://github.com/maickrau/ribotin/commit/298c7152805ee643214b271f73ae54ba415f06bd) does this now
